openapi: 3.0.0
info:
  title: LiteraryHub AI API
  version: 1.0.0
  description: |
    The LiteraryHub AI API provides a robust suite of tools tailored for publishers and authors. It facilitates the creation of audiobooks from texts, generation of custom book covers, and updates to unpublished manuscripts in Word or PDF formats. Key features include plagiarism detection and identification of restricted topics, empowering users to create and refine content with confidence and compliance. This API serves as a comprehensive resource for automating and enhancing the publication process.
paths:
  /extractor/extract-text-pdf:
    get:
      tags:
        - text extractor
      summary: Extracts text from a PDF file
      description: |
        Extracts text from a PDF file using Optical Character Recognition (OCR) configured specifically for Arabic text. The endpoint requires a valid PDF file path and returns the extracted text as JSON.
      operationId: extractTextFromPDF
      parameters:
        - in: query
          name: file_path
          required: true
          schema:
            type: string
          description: The path to the PDF file
      responses:
        '200':
          description: Text extraction successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  extracted_texts:
                    type: array
                    items:
                      type: object
                      properties:
                        page_number:
                          type: integer
                        text:
                          type: string
                    description: An array of objects containing page numbers and extracted texts.
        '400':
          description: Invalid file format or file does not exist
        '500':
          description: Error during text extraction
          
  /extractor/extract-text-word:
    get:
      tags:
        - text extractor
      summary: Extracts text from a Word document
      description: |
        Extracts text from a Word (.docx) document using a simple text extraction process. The endpoint needs a valid Word file path and returns the extracted text as JSON.
      operationId: extractTextFromWord
      parameters:
        - in: query
          name: file_path
          required: true
          schema:
            type: string
          description: The path to the Word file
      responses:
        '200':
          description: Text extraction successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  extracted_texts:
                    type: array
                    items:
                      type: object
                      properties:
                        page_number:
                          type: integer
                        text:
                          type: string
                    description: An array of objects containing page numbers and extracted texts.
        '400':
          description: Invalid file format or file does not exist
        '500':
          description: Error during text extraction

  /audiobook/v2/text-to-speech:
    post:
      tags:
        - audiobook
      summary: Converts text to speech
      description: This endpoint receives text and converts it into spoken audio, returning the path to the generated MP3 file. Ideal for transforming book content into an easily accessible audiobook format.
      operationId: textToSpeechV2
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BookTextBody'
      responses:
        '200':
          description: Successfully generated the audio file
          content:
            application/json:
              schema:
                type: object
                properties:
                  audio_book_output_path:
                    type: string
                    description: The server path to the generated audio file in MP3 format
        '400':
          description: Invalid request data
        '500':
          description: Server error
  
  /book-cover/generate:
    post:
      tags:
        - book cover generator
      summary: Generates a custom book cover
      description: |
        Generates a custom book cover based on the provided title, summary, and authors. This endpoint is designed to create visually appealing covers for Arabic books, utilizing details such as the book title, summary, and author names to influence the design. The response includes the generated cover image in PNG format.
      operationId: generateBookCover
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                book_title:
                  type: string
                  description: Title of the book for which the cover is being generated.
                book_summary:
                  type: string
                  description: A brief summary of the book that can influence the cover's design.
                arabic_authors:
                  type: array
                  items:
                    type: string
                  description: List of Arabic authors' names to be featured on the book cover.
                num_inference_steps:
                  type: integer
                  default: 5
                  description: Number of inference steps to be used in the generation process.
                guidance_scale:
                  type: number
                  default: 0.6
                  description: The scale of guidance applied during the cover generation to maintain relevance to the input parameters.
      responses:
        '200':
          description: Successfully generated the book cover.
          content:
            image/png:
              schema:
                type: string
                format: binary
                description: The generated book cover image in PNG format.
        '400':
          description: Invalid input parameters
        '500':
          description: Server error
          
components:
  schemas:
    BookTextBody:
      type: object
      required:
        - text
        - book_name
      properties:
        text:
          type: string
          description: The text to be converted into speech
        book_name:
          type: string
          description: The name of the book associated with the text
